[source]
type = "N2N"
peers = ["relay.cnode-m1.demeter.run:3000"]

[chain]
type = "mainnet"

[intersect]
type = "Origin"

[[filters]]
type = "WorkStats"
max_block_quantity = 2000

[[filters]]
type = "LegacyV1"

[sink]
type = "Assert"
break_on_failure = true
