[source]
type = "N2N"
peers = ["preview-node.world.dev.cardano.org:30002"]

[chain]
type = "preview"

[intersect]
type = "Tip"

[[filters]]
type = "RollbackBuffer"
min_depth = 6

[[filters]]
type = "WorkStats"
max_block_quantity = 20

[[filters]]
type = "LegacyV1"

[sink]
type = "Assert"
break_on_failure = true
