[source]
type = "U5C"
url = "https://cardano-preview.utxorpc-m1.demeter.run"

[source.metadata]
"dmtr-api-key" = "${DMTR_UTXORPC_KEY_PREVIEW}"

[intersect]
type = "Tip"

[[filters]]
type = "WorkStats"
max_block_quantity = 3

[sink]
type = "Noop"
