version: "3"
services:
  elasticsearch:
    image: elasticsearch:8.8.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticsearch-network
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

  kibana:
    image: kibana:8.8.1
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elasticsearch-network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

networks:
  elasticsearch-network:
    driver: bridge
