[source]
type = "N2N"
peers = ["preprod-node.play.dev.cardano.org:3001"]

[chain]
type = "preprod"

[intersect]
type = "Point"
value = [60484568, "874858059dc6c871105b80b38238cf84a91e617b2afde53904407cb2a3299e9d"]

[[filters]]
type = "EmitCbor"

[sink]
type = "SqlDb"
connection = "postgres://postgres:test1234@localhost:15432/oura_test"
apply_cbor_block_template = "INSERT INTO blocks (slot, cbor) VALUES ('{{point.slot}}', decode('{{record.hex}}', 'hex'));"
undo_cbor_block_template = "DELETE FROM blocks WHERE slot = {{point.slot}}"
apply_cbor_tx_template = "INSERT INTO txs (slot, cbor) VALUES ('{{point.slot}}', decode('{{record.hex}}', 'hex'));"
undo_cbor_tx_template = "DELETE FROM txs WHERE slot = {{point.slot}}"
reset_cbor_block_template = "DELETE FROM blocks WHERE slot > {{point.slot}};"
reset_cbor_tx_template = "DELETE FROM txs WHERE slot > {{point.slot}};"

[cursor]
type = "File"
path = "cursor"
