version: "3.1"

services:
  db:
    image: postgres
    # image: mumak
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_db:
