[source]
type = "N2N"
peers = ["backbone.mainnet.cardanofoundation.org:3001"]

[chain]
type = "mainnet"

[intersect]
type = "Tip"

[[filters]]
type = "SplitBlock"

[[filters]]
type = "ParseCbor"

[sink]
type = "AwsSqs"
region = "us-east-1"
# Points at the queue created by the bundled LocalStack (see README). For a real
# AWS queue, use its URL: https://sqs.<region>.amazonaws.com/<account-id>/my-queue
queue_url = "http://localhost.localstack.cloud:4566/queue/us-east-1/000000000000/my-queue"
group_id = "my_group"
