---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${TEST_NAME}
data:
  daemon.toml: |-
    [source]
    type = "N2N"
    address = ["Tcp", "preview-node.world.dev.cardano.org:30002"]
    magic = "preview"
    min_depth = 6

    [source.finalize]
    max_block_quantity = 20

    [source.intersect]
    type = "Tip"

    [sink]
    type = "Assert"
    break_on_failure = true
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${TEST_NAME}
  labels:
    app: ${TEST_NAME}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: ${TEST_NAME}
    spec:
      restartPolicy: "Never"
      containers:
        - name: main
          image: ${TARGET_IMAGE}
          env:
            - name: "RUST_LOG"
              value: "warn"
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 200m
          args:
            - "daemon"
          volumeMounts:
            - mountPath: /etc/oura
              name: oura-config
      volumes:
        - name: oura-config
          configMap:
            name: ${TEST_NAME}
