---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${TEST_NAME}
data:
  daemon.toml: |-
    [source]
    type = "N2N"
    address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
    magic = "mainnet"

    [source.mapper]
    include_block_cbor = true

    [source.finalize]
    max_block_quantity = 500

    [source.intersect]
    type = "Point"
    value = [50030552, "5a091e9831bc0fcd6e6bdb2877036bb260abb4e19195517e4153fb041f956df5"]

    [sink]
    type = "AwsS3"
    region = "us-west-2"
    bucket = "oura-e2e"
    prefix = "${TEST_NAME}-${GITHUB_RUN_NUMBER}/"
    naming = "SlotHash"
    content = "Cbor"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${TEST_NAME}
  labels:
    app: ${TEST_NAME}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: ${TEST_NAME}
    spec:
      restartPolicy: "Never"
      serviceAccount: test
      serviceAccountName: test
      containers:
        - name: main
          image: ${TARGET_IMAGE}
          env:
            - name: "RUST_LOG"
              value: "warn"
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 200m
          args:
            - "daemon"
          volumeMounts:
            - mountPath: /etc/oura
              name: oura-config
      volumes:
        - name: oura-config
          configMap:
            name: ${TEST_NAME}
