apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: elastic
deploy:
  kubectl:
    manifests:
      - k8s/elastic.yaml
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: oura
requires:
  - configs: [elastic]  
deploy:
  kubectl:
    manifests:
      - k8s/oura.yaml
