[source]
type = "N2N"
peers = ["relays-new.cardano-mainnet.iohk.io:3001"]

[intersect]
type = "Tip"

[[filters]]
type = "SplitBlock"

[[filters]]
type = "ParseCbor"

[[filters]]
type = "Select"
skip_uncertain = true

[filters.predicate.match.tx]
metadata = [{
    label = 674,
    value = { text = { regex = "(?i)hello.*world" } }
}]

[sink]
type = "Stdout"
