---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oura
data:
  daemon.toml: |-
    [source]
    type = "N2N"
    address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
    magic = "mainnet"
    since = [4492799, "f8084c61b6a238acec985b59310b6ecec49c0ab8352249afd7268da5cff2a457"]

    [[filters]]
    type = "Fingerprint"

    [sink]
    type = "Logs"
    output_path = "/var/oura/mainnet"
    output_format = "JSONL"
    max_bytes_per_file = 50_000_000
    max_total_files = 200
    compression = true

    [cursor]
    type = "File"
    path = "/var/oura/cursor"

    [metrics]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oura
  labels:
    app: oura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oura
  template:
    metadata:
      labels:
        app: oura
    spec:
      containers:
        - name: main
          image: ghcr.io/txpipe/oura:v1.2.0
          env:
            - name: "RUST_LOG"
              value: "warn"
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 200m
          args:
            - "daemon"
          ports:
            - name: metrics
              containerPort: 9186
          volumeMounts:
            - mountPath: /etc/oura
              name: oura-config
            - mountPath: /var/oura
              name: oura-var
      volumes:
        - name: oura-config
          configMap:
            name: oura
        - name: oura-var
          persistentVolumeClaim:
            claimName: oura
