[source]
type = "N2N"
address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
magic = "mainnet"

[source.finalize]
max_block_quantity = 10

[source.intersect]
type = "Point"
value = [
    50030552,
    "5a091e9831bc0fcd6e6bdb2877036bb260abb4e19195517e4153fb041f956df5",
]

[sink]
type = "GcpPubSub"
topic = "oura-e2e"
