---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oura
data:
  daemon.toml: |-
    [source]
    type = "N2N"
    address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
    magic = "mainnet"
    since = [0, "f0f7892b5c333cffc4b3c4344de48af4cc63f55e44936196f365a9ef2244134f"]
    min_depth = 6

    [[filters]]
    type = "Fingerprint"

    [sink]
    type = "Elastic"
    url = "https://sink-es-http:9200"
    index = "oura.sink.v1.mainnet"
    idempotency = true

    [sink.credentials]
    type = "Basic"
    username = "elastic"

    [cursor]
    type = "File"
    path = "/var/oura/cursor"

    [metrics]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oura
  labels:
    app: oura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oura
  template:
    metadata:
      labels:
        app: oura
    spec:
      containers:
        - name: main
          image: ghcr.io/txpipe/oura:v1.2.0
          env:
            - name: "RUST_LOG"
              value: "warn"
            - name: "OURA_SINK_CREDENTIALS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: elastic
                  name: sink-es-elastic-user
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 200m
          args:
            - "daemon"
          ports:
            - name: metrics
              containerPort: 9186
          volumeMounts:
            - mountPath: /etc/oura
              name: oura-config
            - mountPath: /var/oura
              name: oura-var
      volumes:
        - name: oura-config
          configMap:
            name: oura
        - name: oura-var
          persistentVolumeClaim:
            claimName: oura
