[source]
type = "N2N"
peers = ["127.0.0.1:3001"]

[chain]
type = "preprod"

[intersect]
type = "Point"
value = [
    37225013, "65b3d40e6114e05b662ddde737da63bbab05b86d476148614e82cde98462a6f5"
]

[[filters]]
type = "SplitBlock"

[[filters]]
type = "ParseCbor"

[[filters]]
type = "MatchPattern"

[filters.predicate.output_address.value]
StakeBech32 = "stake_test1upgs54cnpf6m9g36qhrtf4d222urz94x5f09ju9cew4xkxqd0ad6t"

[sink]
type = "Redis"
url = "redis://127.0.0.1/1"
stream_name = "my-stream"
