[source]
type = "N2N"
peers = ["relays-new.cardano-mainnet.iohk.io:3001"]

[intersect]
type = "Point"
value = [
    4493860,
    "ce7f821d2140419fea1a7900cf71b0c0a0e94afbb1f814a6717cff071c3b6afc",
]

[[filters]]
type = "SplitBlock"

[[filters]]
type = "ParseCbor"

[[filters]]
type = "MatchPattern"

[filters.predicate.block]
slot_after = 4493920
slot_before = 4494020

[sink]
type = "Redis"
url = "redis://127.0.0.1/1"
stream_name = "my-stream"
