[source]
type = "N2N"
peers = ["relays-new.cardano-mainnet.iohk.io:3001"]

[intersect]
type = "Point"
value = [37225013, "65b3d40e6114e05b662ddde737da63bbab05b86d476148614e82cde98462a6f5"]

[[filters]]
type = "SplitBlock"

[[filters]]
type = "ParseCbor"

[[filters]]
type = "Select"
skip_uncertain = true

[filters.predicate.Match.Output]
[[filters.predicate.Match.Output.assets]]
[[filters.predicate.Match.Output.assets.assets]]
name = [97, 98, 99, 49]

predicate = """
{
  "any": [
    {
      "match": {
        "output": {
          "assets": [
            {
              "policy": "62326565303462616265643137333230643864316239666639616430383665383666343465633464",
              "name": "61626331"
            }
          ]
        }
      }
    },
    {
      "match": {
        "address": {
          "payment_part": "62326565303462616265643137333230643864316239666639616430383665383666343465633464"
        }
      }
    }
  ]
}
"""

[filters.predicate.Match]

predicate = """
"Match": {
    "Output": {
        "assets": [
            {
                "name": "pepe"
            }
        ]
    }
}
"""


predicate = "output(assets=[asset(policy='0xaBACDAFSDFS'), asset(policy='0xaBACDAFSDFS')]) && output(assets=[asset(policy='0xaBACDAFSDFS')])"

[sink]
type = "Stdout"
