[source]
type = "N2N"
peers = ["relays-new.cardano-mainnet.iohk.io:3001"]

[intersect]
type = "Point"
value = [37225013, "65b3d40e6114e05b662ddde737da63bbab05b86d476148614e82cde98462a6f5"]

[[filters]]
type = "SplitBlock"

[[filters]]
type = "ParseCbor"

[[filters]]
type = "Select"
skip_uncertain = true
pedicate = "addr1qx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3n0d3vllmyqwsx5wktcd8cc3sq835lu7drv2xwl2wywfgse35a3x"

# match any tx that interacts with this particular address
[filters.predicate]
match = "addr1qx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3n0d3vllmyqwsx5wktcd8cc3sq835lu7drv2xwl2wywfgse35a3x"

# match any tx that interacts with this particular stake address
[filters.predicate]
match = "stake178phkx6acpnf78fuvxn0mkew3l0fd058hzquvz7w36x4gtcccycj5"

# match any tx that interacts with this particular asset
[filters.predicate]
match = "asset17jd78wukhtrnmjh3fngzasxm8rck0l2r4hhyyt"

# match any tx that holds a particular datum
[filters.predicate]
match = "datum1httkxyxp8x0dlpdt3k6cwng5pxj3j"

# match any tx that interacts with any of these particular address
[[filters.predicate.any]]
match = "addr1qx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3n0d3vllmyqwsx5wktcd8cc3sq835lu7drv2xwl2wywfgse35a3x"
[[filters.predicate.any]]
match = "addr1w8phkx6acpnf78fuvxn0mkew3l0fd058hzquvz7w36x4gtcyjy7wx"
[[filters.predicate.any]]
match = "addr1vx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzers66hrl8"

# match any tx that interacts with all of these particular address simultaneously
[[filters.predicate.all]]
match = "addr1qx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzer3n0d3vllmyqwsx5wktcd8cc3sq835lu7drv2xwl2wywfgse35a3x"
[[filters.predicate.all]]
match = "addr1w8phkx6acpnf78fuvxn0mkew3l0fd058hzquvz7w36x4gtcyjy7wx"
[[filters.predicate.all]]
match = "addr1vx2fxv2umyhttkxyxp8x0dlpdt3k6cwng5pxj3jhsydzers66hrl8"

# match tx that has an output that simultaneously points to a particular address and contains a particular asset
[filters.predicate.match.output]
address = "addr1w8phkx6acpnf78fuvxn0mkew3l0fd058hzquvz7w36x4gtcyjy7wx"
assets = ["asset17jd78wukhtrnmjh3fngzasxm8rck0l2r4hhyyt"]
datum = "datum1httkxyxp8x0dlpdt3k6cwng5pxj3j"

# match tx that has an output that simultaneously points to a particular address and contains a particular asset
[filters.predicate.match.tx]
address = "addr1w8phkx6acpnf78fuvxn0mkew3l0fd058hzquvz7w36x4gtcyjy7wx"
assets = ["asset17jd78wukhtrnmjh3fngzasxm8rck0l2r4hhyyt"]


pepe = "(addr1xxxx && asset1xxxxx) || addr1bbbb"

[filters.predicate]
any = ["addr1xxxx", "asset1xxxxx"]

[[filters.predicate.any.output]]
address = "addr1xxxx"
assets = ["asset1bbb", "asset1bbb"]

[sink]
type = "Stdout"
